[project]
name = "tradespulse___home_service_automation"
version = "0.1.0"
description = "tradespulse___home_service_automation using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[file-processing,litellm,tools]==1.14.4",
]

[project.scripts]
tradespulse___home_service_automation = "tradespulse___home_service_automation.main:run"
run_crew = "tradespulse___home_service_automation.main:run"
train = "tradespulse___home_service_automation.main:train"
replay = "tradespulse___home_service_automation.main:replay"
test = "tradespulse___home_service_automation.main:test"
run_with_trigger = "tradespulse___home_service_automation.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"

[tool.uv]
override-dependencies = ["litellm<=1.82.6"]
